/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `send_email` - Send Email * `create_task` - Create Task * `call_api` - Call API
 */
export const ActionTypeEnum = {
    SendEmail: 'send_email',
    CreateTask: 'create_task',
    CallApi: 'call_api'
} as const;
export type ActionTypeEnum = typeof ActionTypeEnum[keyof typeof ActionTypeEnum];

