/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatutEnum } from './statutEnum';


export interface ActionPlanifieeList { 
    readonly id: number;
    agenda: number;
    client: number;
    plan_action: number;
    date_execution: string;
    statut: StatutEnum;
}
export namespace ActionPlanifieeList {
}


