/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AgendaDetail { 
    readonly id: number;
    created_at?: string;
    updated_at?: string;
    date_reference: string;
    param_geler_promesse?: number;
    param_anti_spam?: number;
    created_by?: number | null;
    updated_by?: number | null;
}

