/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClientGroupeList { 
    readonly id: number;
    groupe_recouvrement: number;
    client: number;
    actif?: boolean;
}

