/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `AVANT` - Avant * `APRES` - Après
 */
export const DeclencheurEnum = {
    Avant: 'AVANT',
    Apres: 'APRES'
} as const;
export type DeclencheurEnum = typeof DeclencheurEnum[keyof typeof DeclencheurEnum];

