/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EncaissementList { 
    readonly id: number;
    date_encaissement: string;
    montant: string;
    reference: string;
    client: number;
}

