/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `en attente` - En Attente * `payée` - Payée
 */
export const EtatEnum = {
    EnAttente: 'en attente',
    Paye: 'payée'
} as const;
export type EtatEnum = typeof EtatEnum[keyof typeof EtatEnum];

