/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FactureEncaissementList { 
    readonly id: number;
    encaissement: number;
    facture?: number | null;
    devis?: number | null;
    montant_affecte: string;
}

