/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PrioriteEnum } from './prioriteEnum';
import { TypeFd0Enum } from './typeFd0Enum';


export interface GroupeRecouvrementList { 
    readonly id: number;
    libelle: string;
    priorite: PrioriteEnum;
    type: TypeFd0Enum;
}
export namespace GroupeRecouvrementList {
}


