/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class LigneDevis {
  id: number;               // *
  produit_libelle: string;  // *
  total: number;            // *
  quantite: number;         // *
  devis: number ;    // * (id du devis )
  created_at?: string;      // optionnel
  updated_at?: string;      // optionnel
  prix_unitaire?: number;   // optionnel
  created_by?: string;      // optionnel (ou number si id utilisateur)
  updated_by?: string;      // optionnel
  produit?: number;         // optionnel (ou Produit si tu as un modèle)

}
