/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `AUTO` - Automatique * `SEMI_AUTO` - Semi-automatique * `MANU` - Manuel
 */
export const ModeEnum = {
    Auto: 'AUTO',
    SemiAuto: 'SEMI_AUTO',
    Manu: 'MANU'
} as const;
export type ModeEnum = typeof ModeEnum[keyof typeof ModeEnum];

