/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Type306Enum } from './type306Enum';


export interface ModeleRelanceDetail { 
    readonly id: number;
    created_at?: string;
    updated_at?: string;
    type: Type306Enum;
    contenu: string;
    version?: number;
    created_by?: number | null;
    updated_by?: number | null;
}
export namespace ModeleRelanceDetail {
}


