/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Type306Enum } from './type306Enum';


export interface ModeleRelanceList { 
    readonly id: number;
    type: Type306Enum;
    version?: number;
}
export namespace ModeleRelanceList {
}


