/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Notification { 
    readonly id: number;
    readonly user: number | null;
    message: string;
    is_read?: boolean;
    readonly created_at: string;
}

