/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LigneFacture } from './lignesFactures';
import { EtatEnum } from './etatEnum';


export interface PatchedFacture {
    readonly id?: number;
    date_echeance?: string;
    montant?: number;
    etat?: EtatEnum;
    client?: number;
    devis?: number | null;
    direction_technique?: number;
    readonly lignes_facture?: Array<LigneFacture>;
}
export namespace PatchedFacture {
}


