/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchedTarifFraisDossierDetail { 
    readonly id?: number;
    created_at?: string;
    updated_at?: string;
    quantite_min?: number;
    quantite_max?: number | null;
    prix_unitaire?: string;
    montant_max_par_dossier?: string | null;
    created_by?: number | null;
    updated_by?: number | null;
    produit?: number;
    zone?: number | null;
}

