/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkflowStep } from './workflowStep';
import { WorkflowTransition } from './workflowTransition';


export interface PatchedWorkflowDefinition { 
    readonly id?: number;
    code?: string;
    libelle?: string;
    description?: string | null;
    readonly steps?: Array<WorkflowStep>;
    readonly transitions?: Array<WorkflowTransition>;
}

