/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActionTypeEnum } from './actionTypeEnum';


export interface PatchedWorkflowAction { 
    readonly id?: number;
    action_type?: ActionTypeEnum;
    action_params?: any | null;
    sequence_order?: number;
}
export namespace PatchedWorkflowAction {
}


