/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleEnum } from './roleEnum';


export interface PatchedUtilisateur { 
    readonly id?: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username?: string;
    last_name?: string;
    first_name?: string;
    telephone?: string | null;
    email?: string;
    role?: RoleEnum;
    direction?: number | null;
    password?: string;
}
export namespace PatchedUtilisateur {
}


