/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchedFactureEncaissementDetail { 
    readonly id?: number;
    created_at?: string;
    updated_at?: string;
    montant_affecte?: string;
    date_affectation?: string;
    created_by?: number | null;
    updated_by?: number | null;
    encaissement?: number;
    facture?: number | null;
    devis?: number | null;
}

