/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchedClientGroupeDetail { 
    readonly id?: number;
    created_at?: string;
    updated_at?: string;
    actif?: boolean;
    created_by?: number | null;
    updated_by?: number | null;
    groupe_recouvrement?: number;
    client?: number;
}

