/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchedStationEquipementDetail { 
    readonly id?: number;
    created_at?: string;
    updated_at?: string;
    nbre_station?: number | null;
    puissance?: string | null;
    puissance_unite?: string | null;
    caractere_commercial?: string | null;
    nbre_tranche?: number | null;
    largeur_bande?: string;
    largeur_bande_unite?: string;
    localite?: string;
    created_by?: number | null;
    updated_by?: number | null;
    produit?: number | null;
    fiche_technique?: number | null;
    type_station?: number;
    bande_frequence?: number;
}

