/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchedTarifRedevanceGestionDetail { 
    readonly id?: number;
    created_at?: string;
    updated_at?: string;
    puissance_min?: string | null;
    puissance_max?: string | null;
    prix_unitaire?: string;
    montant_min_reseau?: string | null;
    component_desc?: string | null;
    created_by?: number | null;
    updated_by?: number | null;
    produit?: number;
}

