/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Client } from './client';


export interface PatchedDevis { 
    readonly id?: number;
    client?: Client;
    created_at?: string;
    updated_at?: string;
    readonly date?: string;
    montant?: number;
    etat?: string;
    objet?: string | null;
    created_by?: number | null;
    updated_by?: number | null;
    fiche_technique?: number | null;
    direction_technique?: number;
    position?: number;
}

