/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchedPromesseDetail { 
    readonly id?: number;
    created_at?: string;
    updated_at?: string;
    date?: string;
    montant?: string;
    statut?: string;
    created_by?: number | null;
    updated_by?: number | null;
    client?: number;
}

