/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchedClient { 
    readonly id?: number;
    created_at?: string;
    updated_at?: string;
    /**
     * Adresse du siège social
     */
    adresse?: string;
    /**
     * Numéro de téléphone
     */
    telephone?: string;
    /**
     * Type de client
     */
    type?: string;
    /**
     * Dénomination sociale
     */
    denomination_sociale?: string;
    ifu?: string | null;
    /**
     * Numéro du registre de commerce
     */
    rccm?: string;
    /**
     * Qualité
     */
    qualite?: string;
    /**
     * Email
     */
    email?: string;
    /**
     * Site web
     */
    site_web?: string | null;
    /**
     * Localisation Google Maps
     */
    google_maps?: string | null;
    /**
     * Longitude
     */
    longitude?: number | null;
    /**
     * Latitude
     */
    latitude?: number | null;
    /**
     * Nom du représentant légal
     */
    first_name?: string;
    /**
     * Prénom du représentant légal
     */
    last_name?: string;
    /**
     * Téléphone du représentant légal
     */
    telephone_rep_legal?: string | null;
    /**
     * Email du représentant légal
     */
    email_rep_legal?: string | null;
    strategique?: boolean;
    mauvais_payeur?: boolean;
    litige?: boolean;
    created_by?: number | null;
    updated_by?: number | null;
    utilisateur?: number | null;
}

