/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchedLigneDevis { 
    readonly id?: number;
    created_at?: string;
    updated_at?: string;
    quantite?: number;
    prix_unitaire?: number;
    created_by?: number | null;
    updated_by?: number | null;
    devis?: number;
    produit?: number;
}

