/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchedEncaissementDetail { 
    readonly id?: number;
    created_at?: string;
    updated_at?: string;
    date_encaissement?: string;
    montant?: string;
    affecte?: string;
    penalites?: string;
    solde_non_affecte?: string;
    reference?: string;
    objet?: string | null;
    created_by?: number | null;
    updated_by?: number | null;
    mode_paiement?: number;
    client?: number;
}

