/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchedStationCanalDetail { 
    readonly id?: number;
    created_at?: string;
    updated_at?: string;
    nbre_tranche?: number;
    largeur_bande?: string;
    largeur_bande_unite?: string;
    debit?: string | null;
    unite_debit?: string | null;
    created_by?: number | null;
    updated_by?: number | null;
    produit?: number;
    fiche_technique?: number;
    type_station?: number;
    type_canal?: number;
    zone_couverture?: number;
    bande_frequence?: number;
}

