/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Document } from './document';


export interface PatchedDecret { 
    document?: Document;
    date_signature?: string;
    etat?: boolean;
}

