/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `1` - Priorité 1 * `2` - Priorité 2 * `3` - Priorité 3 * `4` - Priorité 4 * `5` - Priorité 5
 */
export const PrioriteEnum = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5
} as const;
export type PrioriteEnum = typeof PrioriteEnum[keyof typeof PrioriteEnum];

