/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class Produit {
    id?: number;
    libelle?: string;
    description?: string | null;
    categorieProduit?: number;
}

