/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `ADMIN` - Administrateur * `TECH` - Direction Technique * `FIN` - Direction Financière * `CLIENT` - Client
 */
export const RoleEnum = {
    Admin: 'ADMIN',
    Tech: 'TECH',
    Fin: 'FIN',
    Client: 'CLIENT'
} as const;
export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];

