/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SanctionList { 
    readonly id: number;
    date_sanction: string;
    montant: string;
    description?: string | null;
}

