/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SanctionDetail { 
    readonly id: number;
    created_at?: string;
    updated_at?: string;
    date_sanction: string;
    montant: string;
    description?: string | null;
    created_by?: number | null;
    updated_by?: number | null;
    client: number;
    type_motif?: number | null;
}

