/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `PREVU` - Prévu * `EXECUTE` - Exécuté
 */
export const StatutEnum = {
    Prevu: 'PREVU',
    Execute: 'EXECUTE'
} as const;
export type StatutEnum = typeof StatutEnum[keyof typeof StatutEnum];

