/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StationCanalList { 
    readonly id: number;
    produit: number;
    type_station: number;
    type_canal: number;
}

