/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `active` - Active * `completed` - Completed * `cancelled` - Cancelled
 */
export const StatusEnum = {
    Active: 'active',
    Completed: 'completed',
    Cancelled: 'cancelled'
} as const;
export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];

