/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TarifFrequenceDetail { 
    readonly id: number;
    created_at?: string;
    updated_at?: string;
    station_type: string;
    puissance_min?: string | null;
    puissance_max?: string | null;
    debit_min_kbps?: number | null;
    debit_max_kbps?: number | null;
    lb_min_mhz?: string | null;
    lb_max_mhz?: string | null;
    prix_unitaire: string;
    condition_desc?: string | null;
    freq_min_mhz?: number | null;
    freq_max_mhz?: number | null;
    created_by?: number | null;
    updated_by?: number | null;
    produit: number;
    couverture?: number | null;
    type_canal?: number | null;
}

