/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TarifFrequenceList { 
    readonly id: number;
    produit: number;
    station_type: string;
    prix_unitaire: string;
}

