/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TarifGarantieDetail { 
    readonly id: number;
    created_at?: string;
    updated_at?: string;
    montant: string;
    created_by?: number | null;
    updated_by?: number | null;
    produit: number;
}

