/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `manual` - Manual * `auto` - Automatic * `timer` - Timer * `event` - Event
 */
export const TriggerTypeEnum = {
    Manual: 'manual',
    Auto: 'auto',
    Timer: 'timer',
    Event: 'event'
} as const;
export type TriggerTypeEnum = typeof TriggerTypeEnum[keyof typeof TriggerTypeEnum];

