/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `EMAIL` - Email * `SMS` - SMS * `COURRIER` - Courrier
 */
export const Type306Enum = {
    Email: 'EMAIL',
    Sms: 'SMS',
    Courrier: 'COURRIER'
} as const;
export type Type306Enum = typeof Type306Enum[keyof typeof Type306Enum];

