/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `DYNAMIQUE` - Dynamique * `MANUEL` - Manuel
 */
export const TypeFd0Enum = {
    Dynamique: 'DYNAMIQUE',
    Manuel: 'MANUEL'
} as const;
export type TypeFd0Enum = typeof TypeFd0Enum[keyof typeof TypeFd0Enum];

