/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatusEnum } from './statusEnum';
import { WorkflowHistory } from './workflowHistory';


export interface WorkflowInstance { 
    readonly id: number;
    workflow: number;
    business_key: string;
    current_step: number;
    readonly current_step_code: string;
    status: StatusEnum;
    started_at?: string;
    updated_at?: string;
    readonly history: Array<WorkflowHistory>;
}
export namespace WorkflowInstance {
}


