/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkflowStep { 
    readonly id: number;
    workflow: number;
    code: string;
    libelle: string;
    sequence_order: number;
    is_start?: boolean;
    is_end?: boolean;
}

