/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkflowAction } from './workflowAction';
import { TriggerTypeEnum } from './triggerTypeEnum';


export interface WorkflowTransition { 
    readonly id: number;
    workflow: number;
    from_step: number;
    readonly from_step_code: string;
    to_step: number;
    readonly to_step_code: string;
    trigger_type: TriggerTypeEnum;
    trigger_params?: any | null;
    readonly actions: Array<WorkflowAction>;
}
export namespace WorkflowTransition {
}


